#!/usr/bin/env python3
"""Generate a staging/feature .env from the production .env.

Usage: python3 scripts/make_nonprod_env.py <staging|feature> [--prod-env PATH]

Copies prod's .env, then:
  - BLANKS everything that could touch money, the live site, or operator
    alert channels (cards, Good360 org + scan credentials, Telegram, SMTP,
    QuickBeed write credentials, LLM API keys)
  - sets ENABLE_AUTO_BUY=false / ENABLE_URL_SCANNING=false
  - points COMPOSE_PROJECT_NAME / DASHBOARD_PROJECT_DIR / MISSIONCONTROL_*
    at the target environment
  - generates a FRESH DASHBOARD_MASTER_KEY and MISSIONCONTROL_API_KEY

Refuses to overwrite an existing .env unless --force is given.
"""
from __future__ import annotations

import argparse
import base64
import os
import re
import secrets
import sys

BLANK_KEYS = {
    # Org purchase accounts + cards — never in non-prod.
    "GOOD360_REVIVING_HOMES_EMAIL", "GOOD360_REVIVING_HOMES_PASSWORD",
    "GOOD360_HOPE4HUMANITY_EMAIL", "GOOD360_HOPE4HUMANITY_PASSWORD",
    "CARD_REVIVING_HOMES_NAME", "CARD_REVIVING_HOMES_NUMBER",
    "CARD_REVIVING_HOMES_EXPIRY", "CARD_REVIVING_HOMES_CVV",
    "CARD_HOPE4HUMANITY_NAME", "CARD_HOPE4HUMANITY_NUMBER",
    "CARD_HOPE4HUMANITY_EXPIRY", "CARD_HOPE4HUMANITY_CVV",
    # Live-site scan login (scanning is disabled here anyway).
    "SCAN_GOOD360_EMAIL", "SCAN_GOOD360_PASSWORD",
    # Operator alert channels — non-prod must not page anyone.
    "TELEGRAM_BOT_TOKEN", "TELEGRAM_GROUP_REVIVING_HOMES",
    "TELEGRAM_GROUP_HOPE4HUMANITY", "TELEGRAM_OPERATOR_CHAT_ID",
    "SMTP_USER", "SMTP_PASSWORD", "ALERT_EMAIL_FROM", "ALERT_EMAIL_TO",
    # QuickBeed CRM — non-prod must not read/write real customer records
    # (Order History auto-sync WRITES back to the CRM).
    "QUICKBEED_API_TOKEN", "QUICKBEED_APP_ID", "QUICKBEED_CONSUMER_ID",
    "QUICKBEED_WEBHOOK_SECRET",
    # Paid LLM agents — no reason to burn tokens from non-prod.
    "OPENAI_API_KEY", "OPENROUTER_API_KEY",
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("env", choices=("staging", "feature"))
    ap.add_argument("--prod-env", default="/root/good-360-bids/.env")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    checkout = f"/root/good-360-bids-{args.env}"
    out_path = os.path.join(checkout, ".env")
    if os.path.exists(out_path) and not args.force:
        print(f"ERROR: {out_path} exists; use --force to regenerate", file=sys.stderr)
        return 1

    with open(args.prod_env) as f:
        lines = f.read().splitlines()

    overrides = {
        "ENABLE_AUTO_BUY": "false",
        "ENABLE_URL_SCANNING": "false",
        "ENABLE_NOTIFICATIONS": "false",
        "COMPOSE_PROJECT_NAME": f"good-360-bids-{args.env}",
        "DASHBOARD_PROJECT_DIR": checkout,
        "MISSIONCONTROL_URL": f"http://missioncontrol-{args.env}:5001",
        "MISSIONCONTROL_INTERNAL_URL": f"http://missioncontrol-{args.env}:5001",
        "DASHBOARD_MASTER_KEY": base64.urlsafe_b64encode(os.urandom(32)).decode(),
        "MISSIONCONTROL_API_KEY": secrets.token_urlsafe(32),
    }

    seen: set[str] = set()
    out: list[str] = [
        f"# {args.env.upper()} environment .env — generated by scripts/make_nonprod_env.py",
        "# from the production .env with purchase/alert secrets blanked.",
        "",
    ]
    key_re = re.compile(r"^([A-Z][A-Z0-9_]*)=")
    for line in lines:
        m = key_re.match(line)
        if not m:
            out.append(line)
            continue
        key = m.group(1)
        seen.add(key)
        if key in overrides:
            out.append(f"{key}={overrides[key]}")
        elif key in BLANK_KEYS:
            out.append(f"{key}=")
        else:
            out.append(line)

    missing = [k for k in overrides if k not in seen]
    if missing:
        out.append("")
        out.append("# ---------- multi-env overrides (keys not present in prod .env) ----------")
        for k in missing:
            out.append(f"{k}={overrides[k]}")

    with open(out_path, "w") as f:
        f.write("\n".join(out) + "\n")
    os.chmod(out_path, 0o600)
    print(f"Wrote {out_path} (project good-360-bids-{args.env}, flags disabled, "
          f"fresh dashboard/API keys, {len(BLANK_KEYS)} secret keys blanked)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
